In [1]:
import torch
import numpy as np
print(f"pytorch version: {torch.__version__}")
print(f"numpy version: {np.__version__}")

pytorch version: 1.7.1
numpy version: 1.19.0


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


## Part 1: Tensor Initialization

In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], 
                         dtype=torch.float32,
                         device=device)
print(my_tensor)
print("-----------------")
print(my_tensor.dtype)
print("-----------------")
print(my_tensor.shape)
print("-----------------")
print(my_tensor.size()) # identical to tensor.shape
print("-----------------")
print(my_tensor.device)
print("-----------------")

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
-----------------
torch.float32
-----------------
torch.Size([2, 3])
-----------------
torch.Size([2, 3])
-----------------
cuda:0
-----------------


### Initialize from numpy array

In [5]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np_arr)
print(type(np_arr))
print("-----------------")

# numpy array to pytorch tensor
tensor = torch.from_numpy(np_arr)
print(tensor)
print(type(tensor))
print("-----------------")

# pytorch tensor to numpy array
np_arr_recovered = tensor.numpy()
print(np_arr_recovered)
print(type(np_arr_recovered))
print("-----------------")

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
-----------------
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
-----------------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
-----------------


### tensor initializations for special tensors

In [6]:
x = torch.empty(size=(2,2))
print(x)
print("-----------------")

x = torch.zeros(size=(2,2))
print(x)
print("-----------------")

x = torch.ones(size=(2,2))
print(x)
print("-----------------")

# Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)
x = torch.rand(size=(2,2))
print(x)
print("-----------------")

# Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 
x = torch.randn(size=(2,2))
print(x)
print("-----------------")

# Return an identity matrix
x = torch.eye(5, 5)
print(x)
print("-----------------")

# Return a 1d tensor with specified start(inclusive), end(exsclusie), step size
x = torch.arange(start=0, end=4, step=1)
print(x)
print("-----------------")

# Return a 1d tensor with specified start(inclusive), end(inclusive), number of points
x = torch.linspace(start=0, end=10, steps=10)
print(x)
print("-----------------")

tensor([[-4.8459e+33,  4.5769e-41],
        [-4.8459e+33,  4.5769e-41]])
-----------------
tensor([[0., 0.],
        [0., 0.]])
-----------------
tensor([[1., 1.],
        [1., 1.]])
-----------------
tensor([[0.0934, 0.5841],
        [0.5338, 0.0417]])
-----------------
tensor([[ 1.7444, -0.9748],
        [ 0.5226, -0.1040]])
-----------------
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
-----------------
tensor([0, 1, 2, 3])
-----------------
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
-----------------


### Inplace tensor initializations
Note that any Pytorch method with an underscore(_) refers to an inplace operation, which means it will modify the existing object instead of creating a new copy

In [8]:
# initialze a tensor filled with elements from standard normal in place 
x = torch.empty((2, 3)).normal_(mean=0, std=1)
print(x)
print("-----------------")

# initialze a tensor filled with elements from unif(0, 1) in place 
x = torch.empty((2, 3)).uniform_(0, 1)
print(x)
print("-----------------")

# fill a tensor with specified number (5)
x = torch.ones((2, 3)).fill_(5)
print(x)
print("-----------------")

tensor([[ 1.2112,  1.7383,  1.3828],
        [-0.1862,  1.3239, -0.5895]])
-----------------
tensor([[0.2946, 0.3312, 0.1492],
        [0.7610, 0.0212, 0.7822]])
-----------------
tensor([[5., 5., 5.],
        [5., 5., 5.]])
-----------------


## Part 2: Type conversion

In [9]:
# default dtype: torch.int64
x = torch.arange(1, 5, 1)
print(x)
print(x.dtype)
print("-----------------")

# convert to bool
x_bool = x.bool()
print(x_bool)
print(x_bool.dtype)
print("-----------------")

# convert to float32 (most commonly used dtype)
x_float = x.float()
print(x_float)
print(x_float.dtype)
print("-----------------")

# convert to float64
x_double = x.double()
print(x_double)
print(x_double.dtype)
print("-----------------")

tensor([1, 2, 3, 4])
torch.int64
-----------------
tensor([True, True, True, True])
torch.bool
-----------------
tensor([1., 2., 3., 4.])
torch.float32
-----------------
tensor([1., 2., 3., 4.], dtype=torch.float64)
torch.float64
-----------------


## Part 3: Tensor Math

In [10]:
x = torch.tensor([1, 3, 5])
y = torch.tensor([10, 8, 6])

# addition
z = x + y
print("Addition")
print(z)
print("-----------------")

# subtraction
print("Subtraction")
z = x - y
print(z)
print("-----------------")

# multiplication (elementwise)
print("Multiplication (elemenwise)")
z = x * y
print(z)
print("-----------------")

# division (elementwise)
print("Division (elemenwise)")
z = x / y
print(z)
print("-----------------")

# dot product
print("Dot product")
z = torch.dot(x, y)
print(z)
print("-----------------")

# exponentiation
print("Exponentiation")
z = x ** 2 # same as x.pow(2)
print(z)
print("-----------------")

# logarithm - base equals e
# input must be a torch.float dtype
z = torch.log(x.float())
print(z)
print("-----------------")

Addition
tensor([11, 11, 11])
-----------------
Subtraction
tensor([-9, -5, -1])
-----------------
Multiplication (elemenwise)
tensor([10, 24, 30])
-----------------
Division (elemenwise)
tensor([0.1000, 0.3750, 0.8333])
-----------------
Dot product
tensor(64)
-----------------
Exponentiation
tensor([ 1,  9, 25])
-----------------
tensor([0.0000, 1.0986, 1.6094])
-----------------


In [11]:
# Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
z = torch.mm(x1, x2) #2x3
print(z)
print(z.shape)

tensor([[1.2946, 0.8078, 1.5901],
        [1.0035, 0.8410, 1.7482]])
torch.Size([2, 3])


In [12]:
# Batch Matrix Multiplication
batch = 32 
n = 10
m = 20
p = 30
x1 = torch.rand((batch, n, m))
x2 = torch.rand((batch, m, p))
z = torch.bmm(x1, x2) 

print(f"x1 with shape {x1.shape}")
print(f"x2 with shape {x2.shape}")
print(f"z with shape {z.shape}")


x1 with shape torch.Size([32, 10, 20])
x2 with shape torch.Size([32, 20, 30])
z with shape torch.Size([32, 10, 30])


In [13]:
# mean, sum, max and other tensor operations
x = torch.tensor([[-3, 8, 10], [8, 2, 6]])
colsum_x = torch.sum(x, dim=0)
print("torch sum")
print(colsum_x)
print("-----------------")
rowsum_x = torch.sum(x, dim=1)
print(rowsum_x)
print("-----------------")

rowmax_values, rowmax_indicies = torch.max(x, dim=1)
print("torch max")
print(rowmax_values)
print(rowmax_indicies)
print("-----------------")

x_abs = torch.abs(x)
print("torch abs")
print(x_abs)
print("-----------------")

colmean_x = torch.mean(x.float(), dim=0)
print("torch mean")
print(colmean_x)
print("-----------------")


x_clamped = torch.clamp(x, min=0, max=3)
print("torch clamp")
print(x_clamped)
print("-----------------")



torch sum
tensor([ 5, 10, 16])
-----------------
tensor([15, 16])
-----------------
torch max
tensor([10,  8])
tensor([2, 0])
-----------------
torch abs
tensor([[ 3,  8, 10],
        [ 8,  2,  6]])
-----------------
torch mean
tensor([2.5000, 5.0000, 8.0000])
-----------------
torch clamp
tensor([[0, 3, 3],
        [3, 2, 3]])
-----------------


## Part 4: Broadcasting

In [14]:
x1 = torch.rand((3, 5))
x2 = torch.rand((1, 5))

# x2 will be firstly broadcasted to 3 by 5, then do the subtraction
# broadcating applied here will copy the first row of x2 three times and stack them together
z = x1 - x2

print(f"x1:\n {x1}")
print(f"x2:\n {x2}")
print()
print("Resulting tensor:")
print(z)

x1:
 tensor([[0.4702, 0.9837, 0.2890, 0.5532, 0.2231],
        [0.3634, 0.8649, 0.7174, 0.4346, 0.8095],
        [0.3419, 0.8653, 0.3957, 0.0176, 0.0251]])
x2:
 tensor([[0.6013, 0.6400, 0.0012, 0.3504, 0.8916]])

Resulting tensor:
tensor([[-0.1311,  0.3438,  0.2878,  0.2028, -0.6686],
        [-0.2379,  0.2249,  0.7162,  0.0842, -0.0821],
        [-0.2593,  0.2253,  0.3945, -0.3328, -0.8665]])


In [15]:
# matrix-vector multiplication
x1 = torch.randn(4, 3)
x2 = torch.randn(3)
print(torch.matmul(x1, x2).shape)

# matrix-vector multiplication
x1 = torch.randn(4, 3)
x2 = torch.randn(3)
print(torch.matmul(x1, x2).shape)

# batched matrix x broadcasted vector
batch = 10
x1 = torch.randn(batch, 3, 4)
x2 = torch.randn(4) # [4] -> [4,1] -> [10, 4, 1]
print(torch.matmul(x1, x2).shape) # [10, 3]

# batched matrix x broadcasted matrix
x1 = torch.randn(batch, 3, 4)
x2 = torch.randn(4, 5) # [4, 5] -> [10, 4, 5]
print(torch.matmul(x1, x2).shape)

torch.Size([4])
torch.Size([4])
torch.Size([10, 3])
torch.Size([10, 3, 5])


## Part 5: Indexing

In [16]:
batch = 10
num_features = 20

x = torch.rand((batch, num_features))

print("first sample:")
print(x[0]) #same as x[0, :]

print("first feature")
print(x[:, 0])

print("get first 10 features for the 3rd sample")
print(x[2, :10])

# fancy indexing to access non-contiguous  locations of a tensor
rows = torch.tensor([3, 5])
cols = torch.tensor([2, 8])
print(x[rows, cols])

print("pick element with conditions")
x = torch.arange(10)
print(x[(x<8) & (x>2)])
print(x[x.remainder(2)==0])

print("set values according to certain conditions")
print(torch.where(x>5, x, x*2)) # preserve the values if the value is greater than 5, other wise double it

first sample:
tensor([0.5188, 0.3393, 0.4233, 0.2633, 0.2911, 0.2108, 0.1535, 0.8564, 0.3948,
        0.9893, 0.1660, 0.7462, 0.3142, 0.5593, 0.4792, 0.9205, 0.8772, 0.0752,
        0.6690, 0.9806])
first feature
tensor([0.5188, 0.4800, 0.2569, 0.4574, 0.9137, 0.1602, 0.3561, 0.7827, 0.6193,
        0.1719])
get first 10 features for the 3rd sample
tensor([0.2569, 0.0329, 0.6235, 0.7829, 0.3106, 0.2548, 0.0604, 0.4609, 0.8152,
        0.2571])
tensor([0.2346, 0.6245])
pick element with conditions
tensor([3, 4, 5, 6, 7])
tensor([0, 2, 4, 6, 8])
set values according to certain conditions
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


## Part 6: reshaping

1. torch.view() can only work on **contiguous tensors**, while torch.reshape() can work on both
2. torch.view() has performance advantage over torch.shape()
2. if a tensor is not contiguous, you can still use **tensor.contiguous().view()** to reashape the tensor
3. check this [post](https://discuss.pytorch.org/t/contigious-vs-non-contigious-tensor/30107/2) if you are interested in what is the contiguous tensor in pytorch


In [17]:
x = torch.arange(12) #(12)
x_view = x.view((4, 3))
print(x_view.shape)
x_reshape = x.reshape((4, 3))
print(x_reshape.shape)

torch.Size([4, 3])
torch.Size([4, 3])


In [18]:
# SKIP this if it is too complicated
# this involves how tensor is stored in the memory
# contiguous tensor v.s. non-contiguous tensor
# contiguous tensor: the stride size to move to the next column is 1
x = torch.arange(12).view(4,3)
print(x, x.stride(), x.is_contiguous())
print("-----------------")
y = x.t()
print(y, y.stride(), y.is_contiguous())

# y.view(-1) # this does not work because we cannot use view() on a uncontiguous tensor
y.contiguous().view(-1) # this will work

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) (3, 1) True
-----------------
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]) (1, 3) False


tensor([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

In [19]:
# concatenate tensors 
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
z = torch.cat((x1, x2), dim=0)
print(z.shape)

torch.Size([4, 5])


In [20]:
# flatten the 2nd and 3rd dimension of feature matrix to a single dimension
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [21]:
# switch the axis
x = torch.rand((batch, 2, 5))
z = x.permute(0, 2, 1) # keep the batch dimension the same and switch the other two dimensions
print(z.shape)

torch.Size([64, 5, 2])


In [22]:
# add a dimension of size 1
x = torch.arange(10)
print(x.unsqueeze(0)) #[10] -> [1,10]
print(x.unsqueeze(1)) #[10] -> [10,1]

# remove a dimension of size 1
x = torch.arange(10).reshape(1, 10)
print(x.squeeze(0)) #[1, 10] -> [10]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Excercises
1. Create a 2D tensor (elements drawn from standatd normal) and then add a dimension of size 1 inserted at dimension 1
2. Remove the extra dimension you just added to the previous tensor
3. Create a random tensor of shape 5x3 uniformly drawn from the interval [3, 7)
4. Retrieve the indices of all the non-zero elements in the tensor torch.Tensor([1, 1, 2, 0, 3])
5. Create a random tensor of size (3,1) and horizontally stack four copies together. (the result tensor shape is (3,4))
